#!/data/data/com.termux/files/usr/bin/bash
#Coded by Ivam3 on jun 27 2018
#
source $PREFIX/libexec/colors

#BANNER
	echo -e "$blue
		       -{ Ivam3  by  Cinderella }

			    { Support Team }
$cyan
			       BANNER#by#
			   #####Edqueru######
			Ariel_conmed#Adims#Shanks
		      SrMuerto SO-android #Narva3z
		    LawLiet SalvadorContreras Gospit
		   THANKS##TO##MY##MASTER##CINDERELLA$blue
		  OFFICIAL ANDRAX LATINAMERICA SUPPORT$cyan
		   #>:    #Community##of#The##    :<#
		    #>:      >Next#Hackers<      :<#
		     #>:      HayateGenkko      :<#
		      ###People#do ## ##not####die
		       \##If#they# ## still#live/
		        #In#####the#hearts#of###
			#they#   #Loved   #ON3s
			  #We#   #Love#   Her
			    We   Mi  ss   Her
			    QE   PD  QE  QED
			    QE   PD  QE   PD
			    QE   PD  QE   PD
			    Q    #E   P    #D
			    QE   PD  QE   PD
			    QE   PD  QE   PD
			         QE       PD
$blue
			[---] Goin me on [---]

	       [-] www.youtube.com/c/ivam3bycinderella [-]
	              [-] t.me/andraxspanish [-]
			  [-] t.me/ivam3 [-]
				 \n "
